export default [
  {
    id: 1,
    img1: "/image/writer.jpg",
    sale: "Sold out",
    img2: "/image/star.png",
    rate: 5,
    country: "USA",
    lifeLesson: "Life lessons with Katie",
    price: `$ ${136}`,
    openspot: 0,
  },
  {
    id: 2,
    img1: "/image/girl1.jpg",
    sale: "Sold out",
    img2: "/image/star.png",
    rate: 4.9,
    country: "England",
    lifeLesson: "Learn Digital Marketing",
    price: `$ ${143}`,
    openspot: 0,
  },
  {
    id: 3,
    img1: "/image/girl2.jpg",
    sale: "Order",
    img2: "/image/star.png",
    rate: 4,
    country: "Britain",
    lifeLesson: "Learn abroad in Sidney",
    price: `$ ${70}`,
    openspot: 5,
  },
  {
    id: 4,
    img1: "/image/girl3.jpg",
    sale: "Sold out",
    img2: "/image/star.png",
    rate: 3.9,
    country: "Asia",
    lifeLesson: "Let's learn coding",
    price: `$ ${500}`,
    openspot: 0,
  },
  {
    id: 5,
    img1: "/image/girl3.jpg",
    sale: "Order",
    img2: "/image/star.png",
    rate: 3.9,
    country: "Asia",
    lifeLesson: "Let's learn coding",
    price: `$ ${500}`,
    openspot: 9,
  },
];
